apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: default
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "info"
    defaultEntryPoints = ["http","https"
    [entryPoints
      [entryPoints.http
      address = ":80"
      compress = true
      [entryPoints.https
      address = ":443"
      compress = true
        [entryPoints.https.tls
          [[entryPoints.https.tls.certificates]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
    [ping
    entryPoint = "http"
    [kubernetes
      [kubernetes.ingressEndpoint
      publishedService = "default/traefik"
    [traefikLog
      format = "json"
    [metrics
      [metrics.prometheus
        entryPoint = "traefik"
