apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3scale-routes-http
spec:
  entryPoints:
    - web
  routes:
  - match: HostRegexp(`{domain:traefik.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:backend-listener..hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: backend-listener
      port: 3000
      passHostHeader: true
  - match: HostRegexp(`{domain:.*-apicast-staging.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: apicast-staging
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:.*-apicast-production.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: apicast-production
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:.*}`)
    kind: Rule
    services:
    - name: system
      port: 3000
      passHostHeader: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3scale-routes-https
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
  - match: HostRegexp(`{domain:traefik.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: traefik
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:backend-listener..hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: backend-listener
      port: 3000
      passHostHeader: true
  - match: HostRegexp(`{domain:.*-apicast-staging.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: apicast-staging
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:.*-apicast-production.hackfest.[a-z]+.mc.3sca.net}`)
    kind: Rule
    services:
    - name: apicast-production
      port: 8080
      passHostHeader: true
  - match: HostRegexp(`{domain:.*}`)
    kind: Rule
    services:
    - name: system
      port: 3000
      passHostHeader: true