apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3scale-routes
spec:
  entryPoints:
    - web
    - websecure
  routes:
  # - match: Host('backend-listener.hackfest.aws.mc.3sca.net')
  #   kind: Rule
  #   services:
  #   - name: backend-listener
  #     port: 3000
  #     passHostHeader: true
  # - match: HostRegexp(`.*-apicast-staging.hackfest.aws.mc.3sca.net`)
  #   kind: Rule
  #   services:
  #   - name: apicast-staging
  #     port: 8080
  #     passHostHeader: true
  # - match: HostRegexp(`.*-apicast-production.hackfest.aws.mc.3sca.net`)
  #   kind: Rule
  #   services:
  #   - name: apicast-production
  #     port: 8080
  #     passHostHeader: true
  # - match: HostRegexp(`.*`)
  #   kind: Rule
  #   services:
  #   - name: system-app
  #     port: 3000
  #     passHostHeader: true