apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
  name: system-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
  volumeMode: Filesystem
