apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: $(APP_LABEL)
    threescale_component: system
    threescale_component_element: app
  name: system-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: $(RWX_STORAGE_CLASS)
